### ISSUE TITLE
[Request]Add compatibility with NT 2.0 ESP Version

### ISSUE THREAD

**Issue by Markul91** [tangtang95/ff7-60fps-nt-plugin-mod#1]
Hi , could be posible to add compatibility in the mod.xml with the ID efc4bc61-7f81-4635-b583-f52c5c9d239f  ?. Is the ID of the Spanish version of New Threat 2.0.

**Comment by tangtang95** [comment]
If I substitute the original new threat ID with the ID you provided and create another IRO with only that change. Is it fine for you? 

Basically I will replace all the text with "efc4bc61-7f80-4635-b583-f52c5c9d239f" with "efc4bc61-7f81-4635-b583-f52c5c9d239f" in `mod.xml` and then create a new mod together with the existing one. Then you can just add the new IRO mod link in your catalog. Maybe I will change also the mod name and mod id.

**Comment by tangtang95** [comment]
@Markul91 try this one with a different mod.xml
[Uploading ff7-60fps-nt-plugin-mod-spanish.zip…]()

**Comment by tangtang95** [comment]
[ff7-60fps-nt-plugin-mod-spanish.zip](https://github.com/user-attachments/files/17018443/ff7-60fps-nt-plugin-mod-spanish.zip)

@Markul91 Try this version. It contains 
 a modified mod.xml

**Comment by Markul91** [comment]
@tangtang95  Yes, it works. I can execute both mods activated. This new .IRO its gonna be added to the catalog? or i must maintain it by myself?

**Comment by tangtang95** [comment]
It will be maintained in this repo, but you need to add it in your catalog. In the next release, there will be another ".iro" file

**Comment by tangtang95** [comment]
> @tangtang95  Yes, it works. I can execute both mods activated. This new .IRO its gonna be added to the catalog? or i must maintain it by myself?

By both mods are you referring to New Threat 2.0 ESP and this new IRO right?

**Comment by Markul91** [comment]
> > @tangtang95  Yes, it works. I can execute both mods activated. This new .IRO its gonna be added to the catalog? or i must maintain it by myself?
> 
> By both mods are you referring to New Threat 2.0 ESP and this new IRO right?

Yes, yes, the ESP version , and the new .IRO .

**Comment by Markul91** [comment]
> It will be maintained in this repo, but you need to add it in your catalog. In the next release, there will be another ".iro" file

Ok, perfect. Thank you so much for the quick response :)

**Comment by tangtang95** [comment]
Released. You can use this link in your catalog for the download link: https://github.com/tangtang95/ff7-60fps-nt-plugin-mod/releases/download/v1.03/ff7-60fps-nt-plugin-mod.ESP.iro

**Comment by tangtang95** [comment]
Hello @Markul91, for your information, the new release 1.04 removed the hard compatibility dependency. So, I decided to remove the ESP iro version. You can now use the original IRO for New Threat 2.0 ESP
